### ISSUE TITLE
Underscore doesn't display properly in the update dialog

### ISSUE THREAD

**Issue by linyuanjing** [suever/matlab-plugins#1]

**Comment by suever** [comment]
Was the text that was italicized the "t1" part in this commit message: "Merge branch 'master' of gitlab.com:fornwalt/compute_t1_plugin"? If so, that's actually the expected behavior because the contents of the update box are purely the commit message (interpreted as markdown)

**Comment by linyuanjing** [comment]
Yes that's what it was.
